//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dad_ZamfirTamina
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cont
    {
        public Cont()
        {
            this.Rulaje = new HashSet<Rulaje>();
        }
    
        public int Id { get; set; }
        public string Simbol { get; set; }
        public string Denumire { get; set; }
        public Nullable<decimal> SID { get; set; }
        public Nullable<decimal> SIC { get; set; }
    
        public virtual ICollection<Rulaje> Rulaje { get; set; }
    }
}
