//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dad_ZamfirTamina
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rulaje
    {
        public int Id { get; set; }
        public Nullable<int> IdCont { get; set; }
        public Nullable<int> IdOperatie { get; set; }
        public Nullable<decimal> SumaD { get; set; }
        public Nullable<decimal> SumaC { get; set; }
    
        public virtual Cont Cont { get; set; }
        public virtual Operatie Operatie { get; set; }
    }
}
