//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dad_ZamfirTamina
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwBalantaDeVerificare
    {
        public int Id { get; set; }
        public string Simbol { get; set; }
        public string Denumire { get; set; }
        public Nullable<decimal> SID { get; set; }
        public Nullable<decimal> SIC { get; set; }
        public Nullable<decimal> Rulaj_D { get; set; }
        public Nullable<decimal> Rulaj_C { get; set; }
        public Nullable<decimal> TSD { get; set; }
        public Nullable<decimal> TSC { get; set; }
    }
}
